### ISSUE TITLE
Issue related to prefix

### ISSUE THREAD

**Issue by chiragparekh** [gsklee/ngStorage#163]
Hello,

I tried to change to prefix to empty but I am not able to change it to empty.

I mean this: $localStorageProvider.setKeyPrefix('');

How to do this?

**Comment by egilkh** [comment]
Hi. 

ngStorage has always used a prefix so we haven't been too concerned about allowing no prefix.

Do you get any errors or does it save wrong?

**Comment by chiragparekh** [comment]
Thanks for your reply.

May be I can set the blank prefix but I found another problem that I can not get the value of the $localStorage variable which is not string I mean not enclosed within double quotes otherwise it gives me error.

**Comment by SeanBlader** [comment]
It fails to load and causes an error in Angular.

I unfortunately need to write cookies for an existing application and cannot use any prefixes, so this is a deal breaker for me. :-(

**Comment by egilkh** [comment]
@SeanBlader Would you be so kind as to provide the error you are getting?

**Comment by egilkh** [comment]
@chiragparekh Not sure what you mean, do you have an example of this recent behaviour of double quotes?

**Comment by fouadkada** [comment]
$localStorage adds double quotes, using version 0.3.9

**Comment by benjamincharity** [comment]
This is the error I see when trying to set an empty prefix:

![screen shot 2015-10-13 at 10 13 59 am](https://cloud.githubusercontent.com/assets/270193/10457189/3615ddfe-7193-11e5-9abe-44fd32cbb7c3.png)

**Comment by dogancelik** [comment]
I'm using Angular 1.4.7 and 0.3.6 for ngStorage.

I'm getting this error:

```
Failed to instantiate module App due to:
TypeError: $localStorageProvider.setKeyPrefix is not a function
    at ./index.js:100:25
    at Object.e [as invoke] (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:39:193)
    at d (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:37:374)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:37:498
    at m (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:7:322)
    at h (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:37:275)
    at fb (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:41:35)
    at d (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:19:463)
    at zc (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:20:274)
    at Zd (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular.min.js:19:83
```

Config:

```js
angular
.module('App')
.config(['$localStorageProvider', function ($localStorageProvider) {
  $localStorageProvider.setKeyPrefix('test');
  // or $localStorageProvider.setKeyPrefix('');
}])
```

**Comment by dogancelik** [comment]
Double quotes issue is related to window.localStorage, I'm assuming there is no double quotes in $localStorage.

If you do:

```js
$localStorageProvider.setKeyPrefix('test-');
// ...
$localStorage.foo = "asd"
```

When you check the value in window.localStorage:

```js
>> localStorage.getItem('test-foo')
<< ""asd""

>> localStorage.getItem('test-foo').length
<< 5
```

**Comment by dkordik** [comment]
This issue makes ngStorage not well suited for pulling an existing localStorage value off of a page (one that is set by something other than ngStorage)
