### ISSUE TITLE
ngStorage crashes the whole application when ran in an iframe

### ISSUE THREAD

**Issue by jantimon** [gsklee/ngStorage#57]
**Chrome** prevents access to cookies and local storage if the page is load in an **cross domain iframe** and cookie settings are set to block third party cookies.

<pre>
Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Error (native)
    at Object.<anonymous> (https://rawgit.com/gsklee/ngStorage/master/ngStorage.js:42:41)
    at Object.d [as invoke] (https://code.angularjs.org/1.1.5/angular.min.js:28:304)
    at https://code.angularjs.org/1.1.5/angular.min.js:30:39
    at c (https://code.angularjs.org/1.1.5/angular.min.js:27:142)
    at d (https://code.angularjs.org/1.1.5/angular.min.js:27:276)
    at Object.instantiate (https://code.angularjs.org/1.1.5/angular.min.js:28:434)
    at https://code.angularjs.org/1.1.5/angular.min.js:53:326
    at https://code.angularjs.org/1.1.5/angular.min.js:44:274
    at n (https://code.angularjs.org/1.1.5/angular.min.js:7:74) 
</pre>

To demonstrate the issue I took the [demo from your readme.md](http://run.plnkr.co/plunks/o4w3VGqmp8opfrWzvsJy/) and put it into a **[jsfiddle iframe](http://jsfiddle.net/e8y85/)**.

As you can see the application crashes and can't even bootstrap in Chrome

**Comment by egilkh** [comment]
Your example does not crash now using latest (tagged 0.3.3).
